version: 'v2'
services:
  vprodb:
    build:
       context: ./Dockerfiles/db
    image: butler123/db
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodapp:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=vprodapp
  vprocache01:
      image: memcahed
      ports: 
        - "1121:1121"

  vpromq01:
      image: rabbitmq
      ports: 
        - "15672:15672"
      environment:
         - rabbitmq.username=guest
         - rabbitmq.password=guest

  vprodapp:
    build:
       context: ./Dockerfiles/app
    image: butler123/app
    container_name: vprodapp
    ports:
      - "8080:8080"
    volumes:
      - vprodappdata:/usr/local/tomcat/webapps
    
  vprodweb:
    build:
       context: ./Dockerfiles/aweb
    image: butler123/web
    container_name: vprodweb
    ports:
      - "80:80"
volumes: 
   vprodbdat: {}
   vproappdata: {}    
    